apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod  # You can update this name as needed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: arinifinity/lucky-images:latest
          imagePullPolicy: Always  # Or change to IfNotPresent for production
